FROM node:20-alpine
WORKDIR /app
COPY backend/package.json ./package.json
COPY backend/package-lock.json ./package-lock.json
RUN npm install
COPY . .
COPY backend/. .

COPY backend/src/db/prisma ./prisma
COPY backend/tsconfig.json ./tsconfig.json
ENV DATABASE_URL=postgresql://postgres:mysecretpassword@localhost:5432/postgres
RUN echo $DATABASE_URL
RUN DATABASE_URL=$DATABASE_URL npx prisma migrate dev
RUN npx prisma generate
RUN npm run build
EXPOSE 3000

CMD ["node","./dist/index.js"]